collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7111228
  brandStrength: 0.5644469
  lightness: 0.8023339
  brandColors:
    - '#F3F4F4'
    - '#5D5B5D'
    - '#000000'
    - '#D0C6BD'
    - '#9A785D'
  rhythmicContrast: 0.1510649
typography_spectrum: 0.4737727
layout_spectrum: 0.243213
name: Esplux
